@base_url = http://localhost:8080
# uncomment this to hit the deployed API instead:
# @base_url = https://tic-tac-toe-api.nreyes.dev/api

### 
# @name createGame
POST {{base_url}}/game
# uncomment this to create games with the same player
# X-Player-Id: {{playerId}}

###

@playerId = {{createGame.response.body.$.player_id}}
@gameId   = {{createGame.response.body.$.game_id}}

### 
GET {{base_url}}/game/{{gameId}}
X-Player-Id: {{playerId}}

### 
POST {{base_url}}/game/{{gameId}}/move
Content-Type: application/json
X-Player-Id: {{playerId}}

{
  "x": 1,
  "y": 1
}

### 
GET {{base_url}}/game/history
Content-Type: application/json
X-Player-Id: {{playerId}}

### 